openapi: 3.0.3
info:
  title: Additional PreAuth endpoint
  description: |-
    This specification of additional endpint in authorisation server to allow starting preauth flow
  version: 0.0.1
servers:
  - url: http://localhost:9000
paths:
  /issuer/preauth:
    post:
      summary: start preauth flow
      description: |-
        init a preauth flow in authentication server. This method is createing a 'code' which will be
        later used to obtain authentcation token. Data passed to this method is attached to the code
        so that later access token issed by the code will contain bussines data (like user id or credential
        type)
      parameters:
        - name: pin
          in: query
          required: false
          schema:
            type: string
          description: |-
            pin nunber which will be required during obtaing access token by preauth flow
          example: 6661
        - name: type
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
          description: |-
            credential type(s) to be allowed for access token which will be returned by this auth flows.
            This is multiple parameter can appear several time in a single request.
          example:
            - https://example.com/covidCertificate
            - https://imsglobal.github.io/Fopenbadges-specification/Fob_v3p0.html#OpenBadgeCredential
        - name: nonce
          in: query
          required: false
          schema:
            type: string
          description: cryptographic nonce which will be returned as initial nonce when access token is obtained
          example: 12asdf334dsz
        - name: user_id
          in: query
          required: false
          schema:
            type: string
          description: id the user who is going to obtain access token. This id will be visible in resource server
          example: abc:user1
        - name: code_challenge
          in: query
          required: false
          schema:
            type: string
          example: E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
          description: |-
            PKCE code challenge to authenticate token request. When this field is passed corresonding code_verifier
            value will be required by token endpoint to successfully process tonken request. This parameter is optional.
      responses:
        '200':
          description: Successful operation return a 'code' as a text
          content:
            text/plain:
              schema:
                type: string
      security: []
